-- 사용자/관리자 테이블
CREATE TABLE users (
                       user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username     VARCHAR2(50) NOT NULL UNIQUE,
                       name         VARCHAR2(100) NOT NULL,
                       password     VARCHAR2(255) NOT NULL,
                       email        VARCHAR2(100),
                       phone        VARCHAR2(20),
                       total_point  NUMBER DEFAULT 0,
                       admin_level  NUMBER(1) DEFAULT 0, -- 0: 사용자, 1: 관리자, 2: 상위 관리자
                       created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 파일 관리 테이블
CREATE TABLE files (
                       file_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       category      VARCHAR2(50),
                       original_name VARCHAR2(255),
                       file_name     VARCHAR2(255),
                       ext           VARCHAR2(10),
                       path          VARCHAR2(500),
                       created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 공지사항 테이블
CREATE TABLE notices (
                         notice_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title      VARCHAR2(200) NOT NULL,
                         content    CLOB,
                         file_id    NUMBER,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_notice_file FOREIGN KEY (file_id) REFERENCES files(file_id)
);

-- 1:1 문의 테이블
CREATE TABLE inquiries (
                           inquiry_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id     NUMBER NOT NULL,
                           title       VARCHAR2(200) NOT NULL,
                           content     CLOB,
                           file_id     NUMBER,
                           admin_reply CLOB,
                           created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_inquiry_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                           CONSTRAINT fk_inquiry_file FOREIGN KEY (file_id) REFERENCES files(file_id)
);

-- 사용자-관리자 1:1 채팅 테이블
CREATE TABLE chat (
                      chat_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id    NUMBER NOT NULL,
                      admin_id   NUMBER NOT NULL,
                      chat_msg   VARCHAR2(4000), -- comment 대신 chat_msg 사용 권장
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                      CONSTRAINT fk_chat_admin FOREIGN KEY (admin_id) REFERENCES users(user_id)
);

-- 자전거 정보 테이블
CREATE TABLE bikes (
                       bike_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       serial_number VARCHAR2(100) UNIQUE,
                       model_name    VARCHAR2(100),
                       status        VARCHAR2(20), -- 예: AVAILABLE, IN_USE, REPAIRING
                       latitude      NUMBER(10, 8),
                       longitude     NUMBER(11, 8),
                       created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 대여 내역 테이블
CREATE TABLE rentals (
                         rental_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id        NUMBER NOT NULL,
                         bike_id        NUMBER NOT NULL,
                         start_time     TIMESTAMP,
                         end_time       TIMESTAMP,
                         total_distance NUMBER(10, 2),
                         created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_rental_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                         CONSTRAINT fk_rental_bike FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
);

-- 결제 내역 테이블
CREATE TABLE payments (
                          payment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id        NUMBER NOT NULL,
                          amount         NUMBER NOT NULL,
                          payment_status VARCHAR2(20), -- 예: COMPLETED, CANCELLED
                          payment_method VARCHAR2(50),
                          transaction_id VARCHAR2(100),
                          created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- 250126
ALTER TABLE users DROP COLUMN card_number;
ALTER TABLE users DROP COLUMN pass;